### ISSUE TITLE
Performance drop on linux with python3.8

### ISSUE THREAD

**Issue by joness95** [nap/jaro-winkler-distance#6]
We use the library on windows and on linux. When using the same code, we got an performance drop around 1/15 :(

**Comment by GustavoPeredo** [comment]
I don't think this is a library related issue. Python should be interpreting the code in similar performance on both windows and linux. 

If performance is a concern, you can try using this merge https://github.com/nap/jaro-winkler-distance/pull/5 which uses Cython to speed up processing

**Comment by joness95** [comment]
Do you use any plattform specific acceleration or pure python? Could also be an dependency related issue.

**Comment by GustavoPeredo** [comment]
It's platform agnostic. You can read more about Cython here: [Python at the speed of C](https://www.infoworld.com/article/3250299/what-is-cython-python-at-the-speed-of-c.html)
